### PR TITLE
Use inverse_of if it's defined for finding reverse migration

### PR DESCRIPTION
**Pull request by ares**
using only key name can detect wrong association when cloning

### CODE REVIEW

**Comment by moiristo** [comment]
Thanks so much! I was already planning on adding something like that to resolve #67. Looks good to me!

**Comment by ares** [comment]
Thank you very much for quick merge @moiristo, is there a chance to have a new version release soon? This issue blocks me in patch for [the Foreman](https://github.com/theforeman/foreman) project.

**Comment by moiristo** [comment]
Yes, I just released this in 2.2.2.

**Comment by ares** [comment]
Thank you very much!

**Pull request merged**
